kind: pipeline
name: testing

steps:
- name: build
  image: node:lts-alpine3.12
  commands:
    - "yarn install"
    - "yarn build"
  when:
    event:
      - pull_request
    branch:
      - main

#trigger:
#  branch:
#    include:
#      - master
#      - feature/*
  
---
kind: pipeline
name: publish 

steps:
- name: publish
  image: plugins/gh-pages
  settings:
    pages_directory: blog
    upstream_name: https://github.com/GeekBeacon/GeekBeacon.github.io.git
    target_branch: master
    force_push: true
    delete: true
    username:
      from_secret: gh_username
    password:
      from_secret: gh_password
    when:
      event:
        exclude:
          - pull_request
      branch:
        - main

depends_on:
  - testing