kind: pipeline
name: testing

steps:
- name: build
  image: node:lts-alpine3.12
  commands:
    - "yarn install"
    - "yarn build"
  when:
    event: [push, pull_request]
    branch: main

---
kind: pipeline
name: publish 

steps:
- name: publish
  image: plugins/gh-pages
  settings:
    pages_directory: blog
    remote_url:  https://github.com/GeekBeacon/GeekBeacon.github.io.git
    upstream-name: origin 
    target_branch: master
    force_push: true
    delete: true
    username:
      from_secret: gh_username
    password:
      from_secret: gh_password
    when:
      event: push
      branch: main

depends_on:
  - testing
